alias g='git'
alias gs='git status'
alias ga='git add -A'
alias gc='git commit'
alias gpl='git pull'
alias gpsh='git push -u origin'
alias gd='git diff'
alias gp='git push'
alias gnb='git checkout -b'
alias gco='git checkout'
alias gb='git branch'
alias rn='git log --pretty="- %s (%an)" $0'
alias gm='git merge'
alias npm-start='npm start -- --https --key=../../localhost-ssl/key.pem --cert=../../localhost-ssl/cert.pem'
alias yarn-start='yarn start --https --key=../../localhost-ssl/key.pem --cert=../../localhost-ssl/cert.pem'